[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "newrelic>=10.12.0",
    "psutil>=7.0.0",
    "python-dotenv>=1.1.0",
]
