name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
      - feature/azure-deploy

env:
  AZURE_CONTAINER_REGISTRY: cogstakacr                # e.g., myacr
  RESOURCE_GROUP: cogstak-realtime-services           # e.g., AzureKubeLoggerRG
  CLUSTER_NAME: <your-aks-cluster-name>               # e.g., AzureKubeLoggerAKS
  IMAGE_NAME: azurekubelogger                         # Image name in ACR
  IMAGE_TAG: ${{ github.sha }}                        # Use commit SHA as the image tag

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        # creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          kubernetes/deployment.yaml
          kubernetes/service.yaml
        images: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}