name: Build and Deploy to AKS

on:
  workflow_run:
    workflows: ["Lint and Test"]
    branches: [main]
    types:
      - completed

env:
  AZURE_CONTAINER_REGISTRY: cogstakacr                # e.g., myacr
  RESOURCE_GROUP: cogstak-realtime-services           # e.g., AzureKubeLoggerRG
  CLUSTER_NAME: cogstak-aks-cluster                   # e.g., AzureKubeLoggerAKS
  IMAGE_NAME: azurekubelogger                         # Image name in ACR
  IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}                        # Use commit SHA from the triggering workflow

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} 
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        # creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          kubernetes/namespace.yaml
          kubernetes/deployment.yaml
          kubernetes/service.yaml
        images: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        namespace: monitoring
